# Assignment 1: NumPy Part 1


## Learning Objectives
This lesson meets the following learning objectives:

- The ability to use Python data structures provided in NumPy.

## Instructions
Read through all of the text in this page. This assignment provides step-by-step training divided into numbered sections. The sections often contain embeded exectable code for demonstration.  Section headers with icons have special meanings:  

- <i class="fas fa-puzzle-piece"></i> The puzzle icon indicates that the section provides a practice exercise that must be completed.  Follow the instructions for the exercise and do what it asks.  Exercises must be turned in for credit.
- <i class="fa fa-cogs"></i> The cogs icon indicates that the section provides a task to perform.  Follow the instructions to complete the task.  Tasks are not turned in for credit but must be completed to continue progress.

Review the list of items in the **Expected Outcomes** section to check that you feel comfortable with the material you just learned. If you do not, then take some time to re-review that material again. If after re-review you are not comfortable, do not feel confident or do not understand the material, please ask questions on Slack to help.

Follow the instructions in the **What to turn in** section to turn in the exercises of the assginment for course credit.

## Background
This notebook is based on the official `NumPy` [documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html).  Unless otherwise credited, quoted text comes from this document.  The Numpy documention describes NumPy in the following way:

> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> - a powerful N-dimensional array object
> - sophisticated (broadcasting) functions
> - tools for integrating C/C++ and Fortran code
> - useful linear algebra, Fourier transform, and random number capabilities
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


## <i class="fa fa-cogs"></i> Notebook Setup
First, we must import the NumPy library.  All packages are imported at the top of the notebook. Execute the code in the following cell to get started with this notebook (type Ctrl+Enter in the cell below)

In [28]:
# Import numpy
import numpy as np

The code above imports numpy as a variable named `np`. We can use this variables to access the functionality of NumPy.  The above is what we will use for the rest of this class.

You may be wondering why we didn't import numpy like this:  
```python
import numpy
```
We could, but the first is far more commonly seen, and allows us to the `np` variable to access the functions and variables of the NumPy package. This makes the code more readable because it is not a mystery where the functions come from that we are using.

## 1. The NumPy Array
### 1.1. Learning
What is an array?  An array is a data structure that stores one or more objects of the same type (e.g. integers, strings, etc.) and can be multi-dimensional (e.g. 2D matricies). In python, the list data type provides this type of functionality, however, it lacks important operations that make it useful for scientific computing.  Therefore, NumPy is a Python package that defines N-dimensional arrays and provides support for linear algebra, and other fucntions useful to scientific computing.

From the Numpy QuickStart Tutorial: 
> NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. 

<div class="alert alert-warning">
    <b>Note</b>:  a "tuple" is a list of numbers. For example, the pair of numbers surrounded by parentheses: (2,4), is a tuple containing two numbers.
</div>

NumPy arrays can be visualized in the following way:

<img src="./media/A01-content_arrays-axes.png">

(image source: https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

Using built-in Python lists, arrays are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = [1,2,3]  

# A 2-dimensional list of numbers.
my_2d_array = [[1,2,3],[4,5,6]]

# A 3-dimensional list of numbers.
my_3d_array = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]

# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

```

Using NumPy, arrays are created using the `np.array()` function. For example, arrays with the same contents as above are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = np.array([1,2,3,4])

# A 2-dimensional list of numbers.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])

# A 3-dimensional list of numbers.
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])

# Two lists of boolean values
a = np.array([True,True,False,False])
b = np.array([False,False,True,True])
```

In NumPy, these arrays are an object of type `ndarray`.  You can learn more about the `ndarray` class on the [NumPy ndarray introduction page](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html). However, this tutorial will walk you through some of the most important attributes, functions and uses of NumPy.

### 1.2. <i class="fas fa-puzzle-piece"></i> Practice

Perform the following in the cell below.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [3]:
Array_1D = np.array([4,6,3,2,5])

In [5]:
Array_2D = np.array([[76,34,2,6,22], [18,34,5,72,10]])

In [7]:
Array_3D = np.array([[[1,3,5],[7,9,11]],[[2,10,5],[4,6,8]]])

## 2. Array Attributes
### 2.1. Learning 
For this section we will retrieve information about the arrays. Once an array is created you can access information about the array such as the number of dimensions, its shape, its size, the data type that it stores, and the number of bytes it is consuming. There are a variety of attributes you can use such as:
+ `ndim`
+ `shape`
+ `size`
+ `dtype`
+ `itemsize`
+ `data`
+ `nbytes`

For example, to get the number of dimensions for an array:
```Python
# Print the number of dimensions for the array:
print(my_3d_array.ndim)
```

You can learn more about these attributes, and others from the [NumPy ndarray reference page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) if you need help understanding the attributes.

Notice that we use dot notation to access these attributes, yet we do not provide the parenthesis `()` like we would for a function call.  This is because we are accessing attributes (i.e. member variables) of the numpy object, we are not calling a function

### 2.1. <i class="fas fa-puzzle-piece"></i> Practice



In the cell below, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [10]:
my_numpy = np.array([[17,21,23],[18,22,24]])

# ndim will return the dimension of the my_numpy array, which is 2
print(my_numpy.ndim)

# shape will return the current shape (tuples) of the array, which is two list consitsting of 3 numbers each (2,3)
print(my_numpy.shape)

# size will return the number of elements that are in the array, which is 6
print(my_numpy.size)

# dtype will return the data type of the elements in the array, which are integers (Int32)
print(my_numpy.dtype)

# itemsize will return the size of one element in the array in bytes, which is 4 for int 32-bit
print(my_numpy.itemsize)

# data will return the starting point of the array data
print(my_numpy.data)

# nbytes will return the size in bytes of all elements in the array, which is 24
print(my_numpy.nbytes)

2
(2, 3)
6
int32
4
24


## 3. Creating Initialized Arrays
### 3.1. Learning

Here we will learn to create initialized arrays. These arrays are pre-initalized with default values.  NumPy provides a variety of functions for creating and intializing an array in easy-to-use functions. Some of these include: 

+ [np.ones()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones): Returns a new array of given shape and type, filled with ones.
+ [np.zeroes()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros): Returns a new array of given shape and type, filled with zeros.
+ [np.empty()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty): Return a new array of given shape and type, without initializing entries.
+ [np.full()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full): Returns a new array of given shape and type, filled with a given fill value.
+ [np.arange()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html#numpy.arange): Returns a new array of evenly spaced values within a given interval.
+ [np.linspace()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html#numpy.linspace): Returns a new array of evenly spaced numbers over a specified interval.
+ [np.random.random](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.random.html): Can be used to return a single random value or an array of random values between 0 and 1.

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output (i.e array) it generates.

NumPy has a large list of array creation functions, you can learn more about these functions on the [array creation routins page](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html) of the NumPy documentation. 

To demonstrate the use of these functions, the following code will create a two-dimensional array with 3 rows and 4 columns (i.e 3 *x* 4) filled with 0's.  

```Python
zeros = np.zeros((3, 4))
```

The following creates a 1D array of values between 3 and 7

```Python
np.arange(3, 7)
```
The result is: `array([3, 4, 5, 6])`

The following creates a 1D array of values between 0 and 10 spaced every 2 integers:

```Python
np.arange(0, 10, 2)
```
The result is: `array([0, 2, 4, 6, 8])`

Notice that just like with Python list slicing, the range uncludes up-to, but not including the "stop" value of the range.


### 3.1. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [40]:
# Initilizing a 3x3 2D array filled with ones by using the np.ones() fucntion and inputting dimensions
ones_array = np.ones((3,3), dtype=int)
print(ones_array) # printing the array
print(' ') #putting space between arrays 

# Initilizing a 2x3x4 2D array filled with zeros by using the np.zeros function and inputting dimensions 
zeros_array=np.zeros((3,4), dtype=int)
print(zeros_array) # printing the array
print(' ') #putting space between arrays 

# Initilizing an empty 2x2 2D array by using the np.empty() function and inputting dimensions
empty_array=np.empty((2,2))
print(empty_array)
print(' ') #putting space between arrays

# Initilizing a 2x3 2D array filled with the integer value 5 
# by using np.full() function and inputting dimensions and fill value
full_array=np.full((2,3), 5, dtype=int)
print(full_array)
print(' ') #putting space between arrays

# Initilizing a 1x3 1D array with increments of 2 from a range of 20 to 30
# by using the np.arrange() function and inputting the start and stop value as well as the increment value
aranged_array=np.arange(20,30,2)
print(aranged_array)
print(' ') #putting space between arrays

# Initilizing an array from an interval of 0 to 20 with even spacing 
# by using the np.linespace() function and inputting the stop and start as well as the number of values to generate
linspace_array=np.linspace(0,20, num=30)
print(linspace_array)
print(' ') #putting space between arrays

# Using np.random.random to generate an array of 10 values from the interval 0.0 to 1.0
random=np.random.random(size=10)
print(random)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
 
[[2.12199579e-314 4.67296746e-307]
 [7.80623720e-321 3.79442416e-321]]
 
[[5 5 5]
 [5 5 5]]
 
[20 22 24 26 28]
 
[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ]
 
[0.8250622  0.2471342  0.41549759 0.09119393 0.58288117 0.85489475
 0.78601349 0.01789158 0.28692283 0.42779932]


## 4. Performing Math and Broadcasting
### 4.1. Learning

At times you may want to apply mathematical operations between arrays. For example, suppose you wanted to add, multiply or divide the contents of two arrays.  If the two arrays are the same size this is straightfoward. However if the arrays are not the same size then it is more challenging.  This is where Broadcasting comes to play:

> The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. (https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)


#### 4.1.1. Arrays of the same size
To demonstrate math with arrays of the same size, the following cell contains code that creates two arrays of the exact same size: _3 x 4_.  Execute the cell to create those arrays:

In [41]:
# Define demo arrays:
demo_a = np.ones((3,4))
demo_b = np.random.random((3,4))

# Print the shapes of each array.
print(f"demo_a shape: {demo_a.shape}")
print(f"demo_b Shape: {demo_b.shape}")

demo_a shape: (3, 4)
demo_b Shape: (3, 4)


Let's print the array to see what they contain:

In [42]:
print(demo_a)
print(demo_b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.73897696 0.43678553 0.03711184 0.13393322]
 [0.41482016 0.60495224 0.26350562 0.44621326]
 [0.81340721 0.17592202 0.60951978 0.6786263 ]]


Because these arrays are the same size we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [43]:
# These arrays have the same shape, 
demo_a + demo_b

array([[1.73897696, 1.43678553, 1.03711184, 1.13393322],
       [1.41482016, 1.60495224, 1.26350562, 1.44621326],
       [1.81340721, 1.17592202, 1.60951978, 1.6786263 ]])

The addition resulted in the corresponding positions in each matrix being added to the other and creating a new matrix.  If you need clarification for how two matricies can be added or subtracted see the [Purple Math](https://www.purplemath.com/modules/mtrxadd.htm) site for examples.

#### 4.1.2. Broadcasting for Arrays of Different Sizes
When arrays are not the same size, you cannot perform simple math.  For this, NumPy provides a service known as "broadcasting". To broadcast, NumPy automatically resizes the arrays to match, and fills in newly created empty cells with values.

To Broadcast, NumPy begins at the right-most dimensions of the array and comparses them then moves left and compares the next set. As long as each set meet the following criteria, Broadcasting can be performed:

+  The dimensions are equal or
+  One of the dimensions is 1.

Consider two arrays of the following dimensions:

+ 4D array 1:  10 x 1 x 3 x 1
+ 3D array 2:       2 x 1 x 9

These arrays are not the same size, but they are compatible with broadcasting because at each diemsion (from right to left) the dimension crtieria is met. When performing math, the value in each dimension of size 1 is broadcast to fill that dimesion (an example is provided below). The resulting array, if the above arrays are added, will be broadcasted to a size of _10 x 2 x 3 x 9_

To demonstrate math with arrays of different size, the following cell contains code that creates two arrays: one of size _3 x 4_ and onther of size _4 x 1_.  Execute the cell to create those arrays:

In [44]:
# Create the arrays.
demo_c = np.ones((3,4))
demo_d = np.arange(4)

# Print the array shapes.
print(f"demo_c shape: {demo_c.shape}")
print(f"demo_d Shape: {demo_d.shape}")

demo_c shape: (3, 4)
demo_d Shape: (4,)


Let's print the array to see what they contain:

In [45]:
print(demo_c)
print(demo_d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


Because these arrays meet our brodcasting requirements, we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [46]:
demo_c + demo_d

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

The addition resulted in the value in each dimension of size 1, being "broadcast" or "streched" throughout that dimesion and then used in the operation. 

#### 4.1.3. Broadcasting With Higher Dimensions

Consider the following arrays of 2 and 3 dimensions. 

In [47]:
demo_e = np.ones((3, 4))
demo_f = np.random.random((5, 1, 4))
print(f"demo_e shape: {demo_e.shape}")
print(f"demo_f shape: {demo_f.shape}")

demo_e shape: (3, 4)
demo_f shape: (5, 1, 4)


Print the arrays to see what they contain:

In [48]:
print(demo_e)
print(demo_f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.1365032  0.28776001 0.88686875 0.27332387]]

 [[0.86312152 0.64527287 0.79016618 0.80195797]]

 [[0.59804958 0.9106744  0.84311757 0.16658795]]

 [[0.41144806 0.51088797 0.2474723  0.79028802]]

 [[0.55869463 0.4109261  0.45702385 0.5255435 ]]]


These two arrays meet the rules for broadcasting becuase they both have a 4 in their last dimension and there is a 1 in the  `demo_f` 2nd dimension.  

Perform the math by executing the following cell:

In [49]:
result = demo_e + demo_f
print(result)

[[[1.1365032  1.28776001 1.88686875 1.27332387]
  [1.1365032  1.28776001 1.88686875 1.27332387]
  [1.1365032  1.28776001 1.88686875 1.27332387]]

 [[1.86312152 1.64527287 1.79016618 1.80195797]
  [1.86312152 1.64527287 1.79016618 1.80195797]
  [1.86312152 1.64527287 1.79016618 1.80195797]]

 [[1.59804958 1.9106744  1.84311757 1.16658795]
  [1.59804958 1.9106744  1.84311757 1.16658795]
  [1.59804958 1.9106744  1.84311757 1.16658795]]

 [[1.41144806 1.51088797 1.2474723  1.79028802]
  [1.41144806 1.51088797 1.2474723  1.79028802]
  [1.41144806 1.51088797 1.2474723  1.79028802]]

 [[1.55869463 1.4109261  1.45702385 1.5255435 ]
  [1.55869463 1.4109261  1.45702385 1.5255435 ]
  [1.55869463 1.4109261  1.45702385 1.5255435 ]]]


The resulting array has dimensions of _5 x 3 x 4_.  For this math to work, the values from `demo_f` had to be "stretched" (i.e. copied and then added) in the second dimension

### 4.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [59]:
# Two differing size arrays that are compatible for broadcasting
Array1=np.random.random((1,3))
Array2=np.random.random((2,1,3))

print(Array1)
print(' ') # space to separate arrays
print(Array2)
print(' ') # space to separate arrays

# Adding the arrays together
Sum=Array1+Array2
print('Addition:')
print(Sum)
print(' ') # space to separate arrays

# Product of the arrays (multiplication)
product=Array1*Array2
print('Multiplication:')
print(product)
print(' ') # space to separate arrays

# Subtracting array 1 from array 2
difference=Array2-Array1
print('Subtraction:')
print(difference)

[[0.78372256 0.66570335 0.74519252]]
 
[[[0.51694031 0.636986   0.95598633]]

 [[0.77095362 0.55888631 0.42531739]]]
 
Addition:
[[[1.30066287 1.30268934 1.70117885]]

 [[1.55467617 1.22458966 1.17050991]]]
 
Multiplication:
[[[0.40513778 0.42404371 0.71239386]]

 [[0.60421374 0.37205249 0.31694334]]]
 
Subtraction:
[[[-0.26678225 -0.02871735  0.21079381]]

 [[-0.01276894 -0.10681703 -0.31987513]]]


In [60]:
# Two differing size arrays that are NOT compatible for broadcasting
Array1=np.random.random((2,3))
Array2=np.random.random((1,2,4))

print(Array1)
print(' ') # space to separate arrays
print(Array2)

# Adding the arrays together
Sum=Array1+Array2
print('Addition:')
print(Sum)

# Product of the arrays (multiplication)
product=Array1*Array2
print('Multiplication:')
print(product)

# Subtracting array 1 from array 2
difference=Array2-Array1
print('Subtraction:')
print(difference)

[[0.07796888 0.53760158 0.61930254]
 [0.1145268  0.1041681  0.92673122]]
 
[[[0.58042415 0.41985545 0.93132881 0.45080016]
  [0.44515835 0.88485399 0.30010104 0.29148084]]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2,4) 

## 5. NumPy Aggregate Functions
### 5.1. Learning

NumPy also provides a variety of functions that "aggregate" data. Examples of aggreagation of data include calculating the sum of every element in the array, calculating the mean, standard deviation, etc.  Below are a few examples of aggregation functions provided by NumPy.

#### 5.1.1 Mathematical Functions
+ [np.sum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html): sums the array elements over a given axis
+ [np.minimum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html#numpy.minimum): compares two arrays and returns a new array of the minimum at each position (i.e. element-wise)
+ [np.maximum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html#numpy.maximum): compares two arrays and returns a new array of the maximum at each position (i.e. element-wise).
+ [np.cumsum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html#numpy.cumsum): returns the cummulative sum of the elements along a given axes.

You can find more about mathematical functions for arrays at the [Numpy mathematical functions page](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

#### 5.1.2 Statistics
+ [np.mean()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html): compute the arithmetic mean along the specified axis.
 [np.median()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html#numpy.median): compute the median along the specified axis.
+ [np.corrcoef()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy.corrcoef): return Pearson product-moment correlation coefficients between two 1D arrays or one 2D array.
+ [np.std()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html#numpy.std): compute the standard deviation along the specified axis.
+ [np.var()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html#numpy.var): compute the variance along the specified axis.

You can find more about statistical functions for arrays at the [Numpy statistical functions page](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html).


Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

For example:
```Python
# Calculate the sum of our demo data from above
np.sum(demo_e)
```


In [61]:
# Calculate the sum of our demo data from above
np.sum(demo_e)

12.0

#### 5.1.3 Logical Aggregate Functions
When arrays contain boolean values there are additional logical aggregation functions you can use: 

 + [logical_and()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html#numpy.logical_and): computes the element-wise truth value of two arrays using AND.
 + [logical_or()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_or.html#numpy.logical_or): computes the element-wise truth value of two arrays using OR.
 + [logical_not()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html#numpy.logical_not):  computes the element-wise truth value of two arrays using NOT.
 
 
You can find more about logical functions for arrays at the [Numpy Logic functions page](https://docs.scipy.org/doc/numpy/reference/routines.logic.html).

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

To demonstrate usage of the logical functions, please execute the following cells and examine the results produced.

### 5.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  

In [62]:
# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

# Perform a logical "or":
np.logical_or(a, b)

array([ True,  True,  True,  True])

In [86]:
# Perform a logical "and":
np.logical_and(a, b)

array([False, False, False, False])

In [87]:
# 5.2 Practice

# Generating the arrays
practice_array1=np.array([[23,18,30,25],[12,22,28,26]])
practice_array2=np.array([4,6,8,3])
practice_array3=np.array([[15,17,22,25],[16,14,22,31]])
print('practice_array1:')
print(practice_array1, '\r\n')
print('practice_array2:')
print(practice_array2, '\r\n')
print('practice_array3:')
print(practice_array3, '\r\n')


# Calling the sum function: sums the elements in an array in a given axis
# Axis not given so it is summing all of the elements in practice_array1
sum_p1_array=practice_array1.sum()
print(sum_p1_array, '\r\n')

# Calling the minimum function: outputs a new array from the input of two arrays
# Output will be same dimension with the minimum between the two arrays
minimum_array=np.minimum(practice_array1,practice_array3)
print(minimum_array, '\r\n')

# Calling the maximum function: outputs a new array from the input of two arrays
# Output will be same dimension with the maximum between the two arrays
maximum_array=np.maximum(practice_array1,practice_array3)
print(maximum_array, '\r\n')

# Calling cumsum function: function output a new array that is the cumulative sum of the elements over a given axis
# No axis was given so the operation is performed on the entirety of the array
cumsum_array=practice_array1.cumsum()
print(cumsum_array, '\r\n')

# Calling mean function: Outputs the mean of the specific axis given
# No axis given, so mean caluclated for the entirey of the array 
p_array2_mean=practice_array2.mean()
print(p_array2_mean, '\r\n')

# Calling np.corrcoef function: outputs the corresponding pearson correlation coefficient matrix
correlation_matrix=np.corrcoef(practice_array3)
print(correlation_matrix, '\r\n')

# Calling np.std function: computes the standard deviation (sd) along a specific axis in an array
# No axis is given so it will output the sd for the entire array
p_array1_sd=np.std(practice_array1)
print(p_array1_sd, '\r\n')

# Calling np.var function: computes the variance along a specific axis in an array 
# No axis is given so it will output the sd for the entire array
p_array2_var=np.var(practice_array2)
print(p_array2_var)

practice_array1:
[[23 18 30 25]
 [12 22 28 26]] 

practice_array2:
[4 6 8 3] 

practice_array3:
[[15 17 22 25]
 [16 14 22 31]] 

184 

[[15 17 22 25]
 [12 14 22 26]] 

[[23 18 30 25]
 [16 22 28 31]] 

[ 23  41  71  96 108 130 158 184] 

5.25 

[[1.         0.93347203]
 [0.93347203 1.        ]] 

5.408326913195984 

3.6875


### 5.3. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  

In [95]:
boolean_array1=np.array([True,True,False,True,True])
boolean_array2=np.array([False,True,True,False,False])

print('boolean_array1:')
print(boolean_array1, '\r\n')
print('boolean_array2:')
print(boolean_array2, '\r\n')

# Calling the logical_and function: applys the logical AND to the two arrays to compute a new array of same deminsion
AND_array=np.logical_and(boolean_array1,boolean_array2)
print(AND_array, '\r\n')

# Calling the logical_or function: applys the logical OR to the two arrays to compute a new array of same deminsion
OR_array=np.logical_or(boolean_array1,boolean_array2)
print(OR_array, '\r\n')

# Calling the logical_not function: applys the logical NOT to the two arrays to compute a new array of same deminsion 
NOT_array=np.logical_not(boolean_array1,boolean_array2)
print(NOT_array, '\r\n')

boolean_array1:
[ True  True False  True  True] 

boolean_array2:
[False  True  True False False] 

[False  True False False False] 

[ True  True  True  True  True] 

[False False  True False False] 



## Expected Outcomes
At this point, you should feel comfortable with the following:
 - What is a NumPy array
 - Using NumPy array attributes 
 - Performing broadcasting
 - Using aggregate functions


## What to Turn in?
Be sure to **commit** and **push** your changes to this notebook.  All practice exercises should be completed.  Once completed, send a **Slack message** to the instructor indicating you have completed this assignment. The instructor will verify all work is completed. 